# Generated by Django 5.1.1 on 2025-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
