from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('home/', views.base, name='home'),
    path('',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('profile/',views.profile,name='profile'),
    path('recruiters-dashboard/',views.rdashboard,name='rdashboard'),
    path('jobs/',views.jobs,name='jobs'),
    path('campany/',views.company,name='company'),
    path('udashboard/',views.udashboard,name='udashboard'),
    path('rhome/', views.rhome, name='rhome'),
    path('rdashboard/',views.rdashboard,name='rdashboard'),
    path('postjob/',views.postjob,name='postjob'),
    path('applicants/',views.applicants,name='applicants'),
    path('rprofile/',views.rprofile,name='rprofile'),
    path('apply/<int:job_id>/',views.apply_to_job,name='apply_to_job'),
    path('job/<int:job_id>/', views.job_details, name='job_details'),
    path("applicant/chat/<int:recruiter_id>/", views.applicant_chat, name="applicant_chat"),
    path("recruiter/chat/<int:applicant_id>/", views.recruiter_chat, name="recruiter_chat"),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('helpcenter/',views.helpcenter,name='helpcenter'),
    path('recruiter_helpcenter/',views.recruiter_helpcenter,name='recruiter_helpcenter'),
    path('contactus/',views.contactus,name='contactus'),
    path('privacy/', views.privacy_policy, name='privacy'),
    path('terms/', views.terms_of_service, name='terms'),
    path('recruiter_terms/', views.recruiter_terms, name='recruiter_terms'),
    path('careers/', views.careers, name='careers'),
    path("jobsearch/", views.jobsearch, name="jobsearch"),
    path('recruiter_about/',views.recruiter_about,name='recruiter_about'),
    path('recruiter_carrers',views.recruiter_carrers,name='recruiter_carrers'),
    path('recruiter_contact',views.recruiter_contact,name='recruiter_contact'),
    path('recruiter_privacy/', views.recruiter_privacy, name='recruiter_privacy'),
    path('recruiter_FAQ/', views.recruiter_FAQ, name='recruiter_FAQ'),
    path('applicant_FAQ/', views.applicant_FAQ, name='applicant_FAQ'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('recruiter/edit/', views.rprofile_edit, name='rprofile_edit'),
    path("application/<int:application_id>/update/", views.update_application_status, name="update_application_status"),
    path('helpcenter/getting_started/', views.getting_started, name='helpcenter/getting_started'),
    path('helpcenter/account_management/', views.account_management, name='helpcenter/account_management'),
    path("helpcenter/job_applications/", views.job_applications, name="job_applications"),
    path("helpcenter/technical_issues/", views.technical_issues, name="technical_issues"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)